server:
  port: 9980

swagger-ui:
  path: /swagger-ui.html

spring:
  application:
    name: SMP-Client
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: 'ALTER SESSION SET CURRENT_SCHEMA=SMP_CLIENT'
      pool-name: client
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: SYSTEM
    password: oracle123
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      show_sql: false
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/migrations
    schemas: SMP_CLIENT

    create-schemas: true

  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
