INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Banco do Brasil');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Bradesco');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Itaú Unibanco');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Santander');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Nubank');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('C6 Bank');
INSERT INTO COMPANY (COMPANY_NAME) VALUES ('Banco Inter');
